name: base
dependencies:
  - numexpr=2.7.3
  - numpy=1.20.1
  - numpy-base=1.20.1
  - numpydoc=1.1.0
  - python=3.8.8
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python-libarchive-c=2.9
  - python-louvain=0.15
